##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  am配置  ###################
am:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  worker-id: 0 # id gen service machine id 0~1023
  redis-host: 127.0.0.1
  redis-port: 6379
  wechat-push-order: false
  lbs-tencent-key: 3K7BZ-HKEKU-TMUVX-BXK7P-XLNCE-CDF44

###################  jwt配置  ###################
jwt:
  encoded-key: L7A/6zARSkK1j7Vd5SDD9pSSqZlqF7mAhiOgRbgv9Smce6tf4cJnvKOjtKPxNNnWQj+2lQEScm3XIUjhW+YVZg==
  #tll-mills:
  #token-type: Bearer

###################  项目启动端口  ###################
server:
  port: 8081

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag


###################  spring配置  ###################
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    converters:
      preferred-json-mapper: fastjson


###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/jfeat/**/mapping/*.xml
  typeAliasesPackage: com.jfeat.**.model
  global-config:
    id-type: 2  #0:数据库ID自增   1:用户输入id   2:全局唯一id(IdWorker)   3:全局唯一ID(uuid)  4: 该类型为未设置主键类型(none)
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

github:
  client:
    clientId: a50d54b76770a9baeab6
    clientSecret: acc77bf7824f9b618e963da04b7addc683c50a7f
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    authSuccessUrl: http://127.0.0.1:8081/#/
    authFailureUrl: http://127.0.0.1:8081/#/register
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

etcd:
  etcdEndpoints: http://127.0.0.1:2379
  serviceName: cr-sys
  serviceEndpoint: http://127.0.0.1:8081
  provideService: false
  subscribeServices: uaas
---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://115.231.156.18:3306/crsys?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: my-secret-pw
      filters: log4j,wall,mergeStat
      initialize: false
      schema: classpath*:sql/**/*-schema.sql
      data: classpath*:sql/**/*-data.sql

logging:
  level: debug
  file: logs/sbseed.log

am:
  shiro-cache-redis: false
---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://192.168.2.153/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root`
      password: root
      filters: log4j,wall,mergeStat
  rabbitmq:
      host: 112.74.26.228
      port: 5672
      username: jfeat
      password: jfeat

logging:
  level: warn
  file: logs/sbseed.log

am:
  shiro-cache-redis: true
  reset-admin-perms: false